### ISSUE TITLE
[ERROR NumCPU]: the number of available CPUs 1 is less than the required 2

### ISSUE THREAD

**Issue by solidnerd** [solidnerd/terraform-k8s-hcloud#19]
This happens when we use `cx11` as default nodes 
```
hcloud_server.master[0] (remote-exec):  [ERROR NumCPU]: the number of available CPUs 1 is less than the required 2
```

to fix this we should use a proper node size like `cx21`

**Comment by fogs** [comment]
Ha, just stumbled over the same thing and updated the defaults in me repo like this ;)
